# Generated by Django 2.2 on 2019-04-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('name', models.CharField(help_text='ex ) 松コース、竹コース、シェフのお任せ10貫', max_length=255, primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sushi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saled_date', models.CharField(max_length=255)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.Menu')),
                ('sushi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.Sushi')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='sushi_lists',
            field=models.ManyToManyField(related_name='menus', to='sales.Sushi'),
        ),
    ]
